defaults:
  - scope:
      path: "process"
    values:
      inProcess: true
  - scope:
      path: "glossary"
    values:
      inGlossary: true
  - scope:
      path: "guides"
    values:
      inGuides: true
